def dummy():
    _('Global')
    _('All Countries')
    _('Canada')
    _('EU')
    _('Germany')
    _('France')
    _('Sweden')
    _('Finland')
    _('Estonia')
    _('Spain')
    _('Singapore')
    _('India')
    _('USA')
    _('Japan')
    _('South Korea')
    _('Taiwan')
    _('Hong Kong')
    _('Australia')
    _('UAE')
    _('Saudi Arabia')
    _('Chile')
    _('Brazil')
    _('Argentina')
    _('Mexico')
    _('South Africa')
    _('Ghana')
    _('Nigeria')
    _('Global')
    _('UK')
    _('Israel')
    _('Switzerland')
    _('China')
    _('Indonesia')
    _('Kenya')
    _('Netherlands')
    _('Denmark')
    _('Norway')
    _('Ireland')
    _('Italy')
    _('Austria')
    _('Poland')
    _('Czech Republic')
    _('Hungary')
    _('Romania')
    _('Greece')
    _('Turkey')
    _('Philippines')
    _('Thailand')
    _('Malaysia')
    _('Vietnam')
    _('New Zealand')
    _('Colombia')
    _('Peru')
    _('Egypt')
    _('Morocco')
    _('Afghanistan')
    _('Albania')
    _('Algeria')
    _('Andorra')
    _('Angola')
    _('Antigua and Barbuda')
    _('Armenia')
    _('Azerbaijan')
    _('Bahamas')
    _('Bahrain')
    _('Bangladesh')
    _('Barbados')
    _('Belarus')
    _('Belgium')
    _('Belize')
    _('Benin')
    _('Bhutan')
    _('Bolivia')
    _('Bosnia')
    _('Botswana')
    _('Brunei')
    _('Bulgaria')
    _('Burkina Faso')
    _('Burundi')
    _('Cabo Verde')
    _('Cambodia')
    _('Cameroon')
    _('Central African Republic')
    _('Chad')
    _('Comoros')
    _('Congo')
    _('Costa Rica')
    _('Croatia')
    _('Cuba')
    _('Cyprus')
    _('Djibouti')
    _('Dominica')
    _('Dominican Republic')
    _('Ecuador')
    _('El Salvador')
    _('Equatorial Guinea')
    _('Eritrea')
    _('Eswatini')
    _('Ethiopia')
    _('Fiji')
    _('Gabon')
    _('Gambia')
    _('Georgia')
    _('Grenada')
    _('Guatemala')
    _('Guinea')
    _('Guyana')
    _('Haiti')
    _('Honduras')
    _('Iceland')
    _('Iran')
    _('Iraq')
    _('Jamaica')
    _('Jordan')
    _('Kazakhstan')
    _('Kiribati')
    _('Kuwait')
    _('Kyrgyzstan')
    _('Laos')
    _('Latvia')
    _('Lebanon')
    _('Lesotho')
    _('Liberia')
    _('Libya')
    _('Liechtenstein')
    _('Lithuania')
    _('Luxembourg')
    _('Madagascar')
    _('Malawi')
    _('Maldives')
    _('Mali')
    _('Malta')
    _('Marshall Islands')
    _('Mauritania')
    _('Mauritius')
    _('Micronesia')
    _('Moldova')
    _('Monaco')
    _('Mongolia')
    _('Montenegro')
    _('Mozambique')
    _('Myanmar')
    _('Namibia')
    _('Nauru')
    _('Nepal')
    _('Nicaragua')
    _('Niger')
    _('North Macedonia')
    _('Oman')
    _('Pakistan')
    _('Palau')
    _('Panama')
    _('Papua New Guinea')
    _('Paraguay')
    _('Portugal')
    _('Qatar')
    _('Rwanda')
    _('Samoa')
    _('San Marino')
    _('Senegal')
    _('Serbia')
    _('Seychelles')
    _('Sierra Leone')
    _('Slovakia')
    _('Slovenia')
    _('Solomon Islands')
    _('Somalia')
    _('Sri Lanka')
    _('Sudan')
    _('Suriname')
    _('Syria')
    _('Tajikistan')
    _('Tanzania')
    _('Togo')
    _('Tonga')
    _('Trinidad and Tobago')
    _('Tunisia')
    _('Turkmenistan')
    _('Tuvalu')
    _('Uganda')
    _('Ukraine')
    _('United Arab Emirates')
    _('United Kingdom')
    _('Uruguay')
    _('Uzbekistan')
    _('Vanuatu')
    _('Vatican City')
    _('Venezuela')
    _('Yemen')
    _('Zambia')
    _('Zimbabwe')
    _('Gov Grants')
    _('Relocation/Growth')
    _('VCs & Accelerators')
    _('Corporate')
    _('Perks')
    _('Cloud & Perks')
